# DO NOT EDIT THIS FILE
#
# To set up cross-compilation, create the file
# $(ROS_ROOT)/rostoolchain.cmake.  It gets read first, prior to 
# any of cmake's system tests.

#############################################################
#
# An example for using the gumstix arm-linux toolchain is below.
# Copy these lines to $(ROS_ROOT)/rostoolchain.cmake to try them out.
#
set(ROOTFS_DIR /home/x0221391/ubuntu_arm/rootfs)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc-4.6)
set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++-4.6)
set(PYTHON_EXECUTABLE /usr/bin/python)
#set(CMAKE_INSTALL_PREFIX /home/x0221391/ubuntu_arm/rootfs/usr/share/ros/hydro)
set(CMAKE_FIND_ROOT_PATH /home/x0221391/ubuntu_arm/rootfs) #/usr/arm-linux-gnueabihf /home/x0221391/ubuntu_arm/rootfs/
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY) 
#set(CATKIN_ENABLE_TESTING ON) # enable if required

#set(BOOST_LIBRARYDIR /home/x0221391/ubuntu_arm/rootfs/usr/lib)
#set(OpenCV_DIR /home/x0221391/ubuntu_arm/rootfs/usr/share/ros/hydro/share/OpenCV)
set(CMAKE_PREFIX_PATH /home/x0221391/ubuntu_arm/rootfs/opt/ros/hydro)#rv
#set(CMAKE_MODULE_PATH /home/x0221391/ubuntu_arm/rootfs/usr/share/ros/hydro/)# optional
set(CMAKE_LIBRARY_PATH /user/x0221391/ubuntu_arm/rootfs/usr/lib/arm-linux-gnueabihf /home/x0221391/ubuntu_arm/rootfs/usr/share/ros/hydro/lib /home/x0221391/ubuntu_arm/rootfs/usr/lib /home/x0221391/ubuntu_arm/rootfs/lib )#rv

SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_CXX_FLAGS " -Wl,--rpath-link,/user/x0221391/ubuntu_arm/rootfs/usr/lib:/user/x0221391/ubuntu_arm/rootfs/usr/lib/arm-linux-gnueabihf -DLINUX_BUILD ")

#############################################################
# Cross-compilation loader
#
# This file is passed to cmake on the command line via
# -DCMAKE_TOOLCHAIN_FILE.

#############################################################
# look for user's toolchain file in $ROS_ROOT/rostoolchain.cmake
# find_file(TOOLCHAINCONFIG rostoolchain.cmake PATHS ENV ROS_ROOT NO_DEFAULT_PATH)
#if(TOOLCHAINCONFIG)
# include(${TOOLCHAINCONFIG})
#endif(TOOLCHAINCONFIG)
#############################################################

