set(_CATKIN_CURRENT_PACKAGE "cam_capture")
set(cam_capture_MAINTAINER "x0221391 <x0221391@todo.todo>")
set(cam_capture_DEPRECATED "")
set(cam_capture_VERSION "0.0.0")
set(cam_capture_BUILD_DEPENDS )
set(cam_capture_RUN_DEPENDS "roscpp")
set(cam_capture_BUILDTOOL_DEPENDS "catkin" "roscpp")