set(_CATKIN_CURRENT_PACKAGE "cam_capture_old")
set(cam_capture_old_MAINTAINER "x0221391 <x0221391@todo.todo>")
set(cam_capture_old_DEPRECATED "")
set(cam_capture_old_VERSION "0.0.0")
set(cam_capture_old_BUILD_DEPENDS )
set(cam_capture_old_RUN_DEPENDS "roscpp")
set(cam_capture_old_BUILDTOOL_DEPENDS "catkin" "roscpp")